// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus"
const application = Application.start()

// import controllers from "./**/*_controller.js"
// controllers.forEach((controller) => {
//   application.register(controller.name, controller.module.default)
// })
import HelloController from "./hello_controller"
application.register("hello", HelloController)